### ISSUE TITLE
Add AWS zone as a parameter to cfnassist

### ISSUE THREAD

**Issue by topchimp** [cartwrightian/cfnassist#15]
Can we add zone as a parameter to cfnassist to make it easier to setup the first time?

**Comment by topchimp** [comment]
this is in addition to the param EC2_REGION, so something like EC2_AVAILABILITYZONE.

**Comment by cartwrightian** [comment]
Done, in latest version. Use ::CFN_ZONE_A, _B or _C in the description of a parameter and the tool will insert the correct name of AZ into the parameter. Full details in the README.md
